# Generated by Django 5.2.8 on 2025-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar_alter_user_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="Email подтверждён"),
        ),
    ]
