# Generated by Django 5.2.8 on 2025-12-08 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attempt",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время отправки"
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Ошибка")],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
